<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Facility Service Definition</string>
  <key>scopeName</key>
  <string>source.fsd</string>
  <key>fileTypes</key>
  <array>
    <string>fsd</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comment</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#attribute-section</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#service-declaration</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#markdown</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>attribute</key>
    <dict>
      <key>match</key>
      <string>([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
      <key>name</key>
      <string>entity.name.type.attribute.fsd</string>
    </dict>
    <key>attribute-parameters</key>
    <dict>
      <key>begin</key>
      <string>(\()</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.parenthesis.open.fsd</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(\))</string>
      <key>endCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.parenthesis.close.fsd</string>
        </dict>
      </dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>([a-zA-Z_][a-zA-Z_0-9]*)\s*:</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.other.attribute.parameter-name.fsd</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=[,)])</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#strings</string>
            </dict>
            <dict>
              <key>match</key>
              <string>[a-zA-Z_0-9]+</string>
              <key>name</key>
              <string>constant.other.attribute.parameter-value.fsd</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>attribute-section</key>
    <dict>
      <key>begin</key>
      <string>\[\s*(?=([a-zA-Z_][a-zA-Z_0-9]*)\b)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.attribute.fsd</string>
        </dict>
      </dict>
      <key>end</key>
      <string>\]</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#attribute</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#attribute-parameters</string>
        </dict>
      </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(?&lt;!/)//</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.comment.fsd</string>
            </dict>
          </dict>
          <key>end</key>
          <string>(?=$)</string>
          <key>name</key>
          <string>comment.line.double-slash.fsd</string>
        </dict>
      </array>
    </dict>
    <key>data-declaration</key>
    <dict>
      <key>begin</key>
      <string>(?=\bdata\b)</string>
      <key>end</key>
      <string>(?&lt;=\})</string>
      <key>name</key>
      <string>meta.data.fsd</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.data.fsd</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.data.fsd</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(data)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#attribute-section</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#member-declaration</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>enum-declaration</key>
    <dict>
      <key>begin</key>
      <string>(?=\benum\b)</string>
      <key>end</key>
      <string>(?&lt;=\})</string>
      <key>name</key>
      <string>meta.enum.fsd</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.enum.fsd</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.enum.fsd</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(enum)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#attribute-section</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>errors-declaration</key>
    <dict>
      <key>begin</key>
      <string>(?=\berrors\b)</string>
      <key>end</key>
      <string>(?&lt;=\})</string>
      <key>name</key>
      <string>meta.errors.fsd</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.errors.fsd</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.errors.fsd</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(errors)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#attribute-section</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>markdown</key>
    <dict>
      <key>begin</key>
      <string>^#\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
      <key>beginCaptures</key>
      <dict>
        <key>0</key>
        <dict>
          <key>name</key>
          <string>markup.heading.fsd</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(?=^#\s+)</string>
      <key>name</key>
      <string>meta.heading.fsd</string>
    </dict>
    <key>member-declaration</key>
    <dict>
      <key>begin</key>
      <string>\b([a-zA-Z_][a-zA-Z_0-9]*):</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.type.member.fsd</string>
        </dict>
      </dict>
      <key>end</key>
      <string>;</string>
      <key>name</key>
      <string>meta.member.fsd</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#type</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
          <key>name</key>
          <string>entity.name.type.reference.fsd</string>
        </dict>
      </array>
    </dict>
    <key>method-declaration</key>
    <dict>
      <key>begin</key>
      <string>(?=\bmethod\b)</string>
      <key>end</key>
      <string>(?&lt;=\})</string>
      <key>name</key>
      <string>meta.method.fsd</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.method.fsd</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.method.fsd</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(method)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\}(?!\s*:)</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#attribute-section</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#member-declaration</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>service-declaration</key>
    <dict>
      <key>begin</key>
      <string>(?=\bservice\b)</string>
      <key>end</key>
      <string>(?&lt;=\})</string>
      <key>name</key>
      <string>meta.service.fsd</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.other.service.fsd</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.service.fsd</string>
            </dict>
          </dict>
          <key>match</key>
          <string>\b(service)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>\{</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>end</key>
          <string>\}</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.block.ts</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comment</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#attribute-section</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#data-declaration</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#enum-declaration</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#errors-declaration</string>
            </dict>
            <dict>
              <key>include</key>
              <string>#method-declaration</string>
            </dict>
          </array>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>name</key>
      <string>string.quoted.double.fsd</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>constant.character.escape.fsd</string>
        </dict>
      </array>
    </dict>
    <key>type</key>
    <dict>
      <key>match</key>
      <string>\b(boolean|bytes|decimal|double|error|int32|int64|map|object|result|string)\b</string>
      <key>name</key>
      <string>storage.type.builtin.fsd</string>
    </dict>
  </dict>
</dict>
</plist>
